  jekyllinit:
    volumes:
        - './:/srv/jekyll'
    ports:
        - '4000:4000'
        - '35729:35729'
    image: jekyll/jekyll:4.2.0
    command: sh -c "chown -R jekyll /usr/gem/ && jekyll new bandsite"  && cd bandsite
    